# Cloudflare Pages configuration
name = "hitky-news"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# KV namespace binding for Pages Functions
[[kv_namespaces]]
binding = "NEWS_ARTICLES"
id = "a2a6e41650d34f129530130830d50889"
