# Wrangler configuration for Hitky News Worker

name = "hitky-news-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Cron trigger - runs every 15 minutes
[triggers]
crons = ["*/15 * * * *"]

# KV namespace binding
[[kv_namespaces]]
binding = "NEWS_ARTICLES"
id = "a2a6e41650d34f129530130830d50889"
